import Head from 'next/head'
import MainPage from '../components/mainPage'

export default function Sobre() {
  return(
    <>
      <Head>
        <title>Sobre Victor Plaza Hotel Arcos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainPage title="Contato">
        contato
      </MainPage>
    </>
  )
}

