import Head from 'next/head'
import MainPage from '../components/mainPage'

export default function Sobre() {
  return(
    <div>
      <Head>
        <title>Sobre Victor Plaza Hotel Arcos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainPage title="Reservas e Tarifas">
        reservas e tarifas
      </MainPage>
 

    </div>
  )
}

