import Head from 'next/head'


export default function Sobre() {
  return(
    <div>
      <Head>
        <title>Sobre Victor Plaza Hotel Arcos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        sobre
      
      </main>
    </div>
  )
}

