import Head from 'next/head'


export default function Sobre() {
  return(
    <div>
      <Head>
        <title>Sobre Victor Plaza Hotel Arcos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-primary text-white'>
        <h1 className='text-2xl bg-secondary p-2'>
        Sobre o Hotel
        </h1>

        <div className='p-2'>
        
			    <p className='pb-2'>“O Victor Plaza Hotel Arcos é o mais novo e luxuoso hotel da cidade de Arcos – Minas Gerais. Possui uma infra-estrutura moderna e completa. Além dos serviços e atendimento de qualidade. Sendo assim, convidamos-lhe a nos fazer uma visita e conhecer nossas instalações. Será um prazer recebê-los.”.</p>
          <p className='pb-2'>Informamos também, que trabalhamos com faturamento para empresas (<a href="/images/pdf/Regulamento.pdf" target="_blank">consulte regulamento</a>). Caso a agência ou a empresa já tiver cadastro no Victor Plaza Hotel em Formiga-MG não há necessidade de efetuar um novo cadastro.</p>	
        </div>


    
      </main>

    </div>
  )
}

